<?php return array (
  'response.php' => '/var/www/html/lgsm-ui/app/protected/class/response.php',
  'mySQLExceptions.php' => '/var/www/html/lgsm-ui/app/protected/class/mySQLExceptions.php',
  'Process.php' => '/var/www/html/lgsm-ui/app/protected/class/Process.php',
  'deploy.php' => '/var/www/html/lgsm-ui/app/protected/class/gearman/deploy.php',
  'DBRESTController.php' => '/var/www/html/lgsm-ui/app/protected/class/DBRESTController.php',
  'QueryEngines.php' => '/var/www/html/lgsm-ui/app/protected/model/QueryEngines.php',
  'Games.php' => '/var/www/html/lgsm-ui/app/protected/model/Games.php',
  'Services.php' => '/var/www/html/lgsm-ui/app/protected/model/Services.php',
  'VboxSoapEndpoints.php' => '/var/www/html/lgsm-ui/app/protected/model/VboxSoapEndpoints.php',
  'Events.php' => '/var/www/html/lgsm-ui/app/protected/model/Events.php',
  'GearmanJobServers.php' => '/var/www/html/lgsm-ui/app/protected/model/GearmanJobServers.php',
  'BaseImages.php' => '/var/www/html/lgsm-ui/app/protected/model/BaseImages.php',
  'Virtualboxes.php' => '/var/www/html/lgsm-ui/app/protected/model/Virtualboxes.php',
  'Github.php' => '/var/www/html/lgsm-ui/app/protected/model/Github.php',
  'GearmanWorkers.php' => '/var/www/html/lgsm-ui/app/protected/model/GearmanWorkers.php',
  'GearmanFunctions.php' => '/var/www/html/lgsm-ui/app/protected/model/GearmanFunctions.php',
);