
INSERT INTO gearman_job_servers(hostname, port, enabled) VALUES('localhost', 4730, 1);

INSERT INTO gearman_functions(function_name, worker_count, enabled) VALUES('deploy', 1, 1);
INSERT INTO gearman_functions(function_name, worker_count, enabled) VALUES('update', 1, 1);

INSERT INTO github(url, branch) VALUES('https://github.com/dgibbs64/linuxgsm.git', 'master');

INSERT INTO query_engines(name, launch_uri) VALUES('None' ,'');
INSERT INTO query_engines(name, launch_uri) VALUES('SOURCE' ,'steam://connect/');
INSERT INTO query_engines(name, launch_uri) VALUES('GOLDSOURCE' ,'steam://connect/');
INSERT INTO query_engines(name, launch_uri) VALUES('Team Speak' ,'ts3server://');
INSERT INTO query_engines(name, launch_uri) VALUES('gamespy1' ,'');
 
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (1, '7 Days To Die', '7DaysToDie', 2.15, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'sdtdserver', 26900, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (1, 'ARK: Survivial Evolved', 'ARKSurvivalEvolved', 2.14, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'arkserver', 7777, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (1, 'ARMA 3', 'Arma3', 2.13, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'arma3server', 2302, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Black Mesa: Deathmatch', 'BlackMesa', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'bmdmserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Blade Symphony', 'BladeSymphony', 2.15, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'bsserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'BrainBread 2', 'BrainBread2', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'bb2server', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Codename CURE', 'CodenameCURE', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'ccserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (3, 'Counter Strike 1.6', 'CounterStrike', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'csserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (3, 'Counter Strike: Condition Zero', 'CounterStrikeConditionZero', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'csczserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Counter Strike: Global Offensive', 'CounterStrikeGlobalOffensive', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'csgoserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Counter Strike: Source', 'CounterStrikeSource', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'cssserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (3, 'Day of Defeat', 'DayOfDefeat', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'dodserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Day of Defeat: Source', 'DayOfDefeatSource', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'dodsserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (3, 'Deathmatch Classic', 'DeathmatchClassic', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'dmcserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Don\'t Starve Together', 'DontStarveTogether', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'dstserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Double Action: Boogaloo', 'DoubleActionBoogaloo', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'dabserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Fistful of Frags', 'FistfulOfFrags', 2.15, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'fofserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Garry\'s Mod', 'GarrysMod', 2.15, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'gmodserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'GoldenEye: Source', 'GoldenEyeSource', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'gesserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Half Life 2: Deathmatch', 'HalfLife2Deathmatch', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'hl2dmserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (3, 'Half Life: Deathmatch', 'HalfLifeDeathmatch', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'hldmserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Half-Life Deathmatch: Source', 'HalfLifeDeathmatchSource', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'hldmsserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Hurtworld', 'Hurtworld', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'hwserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Insurgency', 'Insurgency', 2.15, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'insserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Just Cause 2', 'JustCause2', 2.13, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'jc2server', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Killing Floor', 'KillingFloor', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'kfserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Left 4 Dead', 'Left4Dead', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'l4dserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Left 4 Dead 2', 'Left4Dead2', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'l4d2server', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (1, 'Mumble', 'Mumble', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'mumbleserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'NS2: Combat', 'NS2Combat', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'ns2cserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Natural Selection 2', 'NaturalSelection2', 2.15, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'ns2server', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'No More Room in Hell', 'NoMoreRoomInHell', 2.15, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'nmrihserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (3, 'Half-Life: Opposing Force', 'OpposingForce', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'opforserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Pirates, Vikings, and Knights II', 'PiratesVikingandKnightsII', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'pvkiiserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Project Zomboid', 'ProjectZomboid', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'pzserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Quake Live', 'QuakeLive', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'qlserver', 27960, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Red Orchestra: Ostfront 41-45', 'RedOrchestra', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'roserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (3, 'Ricochet', 'Ricochet', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'ricochetserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Rust', 'Rust', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'rustserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Serious Sam 3: BFE', 'SeriousSam3BFE', 2.13, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'ss3sserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Starbound', 'StarBound', 2.12, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'StarBound', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (3, 'Sven Co-op', 'SvenCoop', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'svencoopserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Team Fortress 2', 'TeamFortress2', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'tf2server', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (3, 'Team Fortress Classic', 'TeamFortressClassic', 2.07, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'tfcserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (4, 'Teamspeak 3', 'TeamSpeak3', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'ts3server', 9987, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Teeworlds', 'Teeworlds', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'twserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (2, 'Terraria', 'Terraria', 0.0, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'terrariaserver', 27015, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (1, 'Unreal Tournament 2004', 'UnrealTournament2004', 2.00, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'ut2k4server', 7777, 1);
INSERT INTO games (query_engines_id, full_name, folder_name, glibc_version_min, hidden) VALUES (1, 'Unreal Tournament 99', 'UnrealTournament99', 2.00, 0);
INSERT INTO services (games_id, script_name, port, is_default) VALUES(LAST_INSERT_ID(), 'ut99server', 7777, 1);

